### ISSUE TITLE
Memory leak going from 3.2.2 to 3.3.0

### ISSUE THREAD

**Issue by smeyfroi** [redis/redis-rb#612] opened 2016-04-25 10:00 UTC
Our app uses [sidekiq ent](http://sidekiq.org/products/enterprise) (latest version) with the redis-rb driver. It also access redis directly using redis-rb to do stuff using redis as a datastore.

After updating gems last week, I saw the active memory on the rails server increase quickly and eventually kill the box.

See attached: the section before the big dip (redeploy) is what happens with redis 3.3.0, where the green [active memory] line eventually maxes out and crashes the server. The section after the redeploy is what happens with redis 3.2.2. The 3.2.2 'active memory' line tends to level out over time roughly at the level where I've taken this screenshot.

![screen shot 2016-04-25 at 10 55 19](https://cloud.githubusercontent.com/assets/203996/14780297/3e219bc0-0ad4-11e6-8006-28ced1ba5b26.png)

Here's another screenshot that shows the different a bit more clearly. Here, the sections up to a redeploy early on 22/4 are 'normal' with active memory sitting reasonably well around 1.17GB. Then after the update to redis-rb you can see the green 'active memory' line climbs and climbs quickly, until catastrophic failure when the kernel kills the process and the cycle continues.

![screen shot 2016-04-25 at 10 57 56](https://cloud.githubusercontent.com/assets/203996/14780384/9af6c5f0-0ad4-11e6-8e95-3e7a746f9ffe.png)

I think this is due to the work that sidekiq does in polling work queues in the background, because once I'd disabled most of our sidekiq workers from doing any work by doing ```return``` from their ```perform``` methods, the memory-chomping continued. So I think this effect may be visible with sidekiq just polling in the background etc. We use sidekiq-ent's [unique jobs](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs) functionality which also polls redis in the background.

I'm not sure how to help debug this but want to raise it because it's probably an important issue unless I'm doing something really weird in my app (which is entirely possible).

Downgrading to 3.2.2 does definitely fix the issue with no other changes (I'm watching the graphs now: they look completely normal again.)

Are you aware of any changes that may have introduced a problem like this? Can I help you debug it?

**Comment by badboy** [comment] 2016-04-25 10:18
Thanks for reporting this. From the top of the head I don't know what could cause this, though we were investigating a (not yet fixed) leak in redis-rb. The change was rather big from 3.2.2 to 3.3.0. We're investigating that.

**Comment by smeyfroi** [comment] 2016-04-25 10:20
Cool. Let me know if there's anything I can do to help. It's easy enough for me to redeploy this test server and see the issue if you need it. :-)

**Comment by kamen-hursev** [comment] 2016-04-26 11:35
I confirm we experience the same issue after upgrading to 3.3.0. We are using Sidekiq, as well, and though it is not heavily loaded its memory usage climbs up more than what we usually monitor. 

In a couple of hours I can confirm if the issue really goes away after I just rolled back to 3.2.2.

**Comment by badboy** [comment] 2016-04-26 14:10
@kamen-hursev, @smeyfroi: Are you using redis-rb in combination with hiredis-rb or without?

**Comment by kamen-hursev** [comment] 2016-04-26 14:14
I'm not using `hiredis-rb`. Just `redis-rb`.

**Comment by badboy** [comment] 2016-04-26 14:17
that confirms my suspicion. I ran a very tiny script through [memory_profile](https://github.com/SamSaffron/memory_profiler): [gist](https://gist.github.com/badboy/ddddc96ebf327cca8c3d1073cfda10c6).
Seems like we're allocating quite some `Timeout` instances.
A run with `hiredis` shows no bigger memory usage.

If possible, can either of you run with hiredis? `gem install hiredis`, then pass `:driver => :hiredis` to `Redis.new`.

**Comment by kamen-hursev** [comment] 2016-04-26 14:29
I won't be able to test `hiredis` in the next 2 weeks. We observe the problem on production only (the test environments are even less loaded) and now is not a suitable time to make experiments on production. So I can report back after minimum two weeks.

**Comment by badboy** [comment] 2016-04-26 14:30
No problem then. I don't expect you to test in production. :)
I hope we have this fixed within less than 2 weeks though

**Comment by smeyfroi** [comment] 2016-04-26 15:12
Hi, I can test that out on my test server. Might be the morning (UK time) time though.

**Comment by badboy** [comment] 2016-04-26 15:13
@smeyfroi Thanks!

**Comment by smeyfroi** [comment] 2016-04-27 09:21
OK I just redeployed with redis3.3.0 and hiredis0.6.1. The graphs look good so far but I'll let it run for a while and report back.

Is hiredis recommended underneath redis-rb for performance? (I never understood this part of the ecosystem.)

**Comment by badboy** [comment] 2016-04-27 09:36
I don't have benchmarks at hand, but yeah, performance is the one reason you might want to use hiredis.
We now know the reason of the leak in the ruby connector in v3.3.0 though and will release a fix ASAP.

**Comment by smeyfroi** [comment] 2016-04-27 09:50
Great! Well done tracking that down.

**Comment by smeyfroi** [comment] 2016-04-27 15:54
Quick note to say that my test server running redis3.3.0 and hiredis0.6.1 looks completely normal at the end of the day here. Guess that helps confirm your forthcoming fix!

**Comment by fertobar** [comment] 2016-06-27 17:07
Hello, any update about this issue?
I'm using 3.2.2. do you recommend me to upgrade to other version or will better to wait?

**Comment by badboy** [comment] 2016-06-27 17:29
@fertobar If you use hiredis-rb you should be fine. 
I'm gonna pull in the required changes for the pure-ruby connector this week.

This is lying around for far too long already :/

**Comment by maia** [comment] 2016-07-16 15:35
@badboy Is there any news regarding the memory leak of 3.3.x? Thanks! 
(I'm running the pure ruby connector on heroku)

**Comment by badboy** [comment] 2016-07-16 16:02
I finally merged the fix now, though can't release the gem on rubygems right now. I'll push it out once I get access.

**Comment by YesThatAllen** [comment] 2016-07-18 19:22
So, this is fixed in [Release v3.3.1](https://github.com/redis/redis-rb/commit/d75708f6e05d9bba7dfec65880f9a55252f3fd2a) ?

**Comment by badboy** [comment] 2016-07-18 20:10
Yes, it should be.

**Comment by maia** [comment] 2016-07-19 20:02
Thanks a lot, much appreciated!

**Comment by badboy** [comment] 2016-07-19 22:01
If someone can confirm this, it would be appreciated. If anything else comes up please report back, until then I'm gonna close this ticket.

**Closed by badboy** 2016-07-19 22:01 UTC

**Comment by mperham** [comment] 2016-07-19 23:21
Looks better, thanks!

**Comment by soylent** [comment] 2016-08-16 18:00
Version 3.3.1 resolves the issue, thanks!

v 3.3.0:
```
allocated memory by gem
-----------------------------------
  26268727  2.3.1/lib
     70216  redis-3.3.0
      6920  [snip]
      4516  other
```

v 3.3.1:
```
allocated memory by gem
-----------------------------------
     67559  redis-3.3.1
      6920  [snip]
      6127  2.3.1/lib
      4516  other
```
