### ISSUE TITLE
Redis::TimeoutError on write of large string

### ISSUE THREAD

**Issue by supercodepoet** [redis/redis-rb#650] opened 2016-11-21 16:37 UTC
I am caching a large string of JSON returned in a Rails action. In redis-rb 3.3.1 it works no problem. In redis-rb 3.3.2 it now returns a Redis::TimeoutError even if I set the timeout on the Rails.cache client to 20 seconds. In redis-rb 3.3.1 it does not take hardly a second to write that large string to Redis. Any ideas?

**Comment by riseshia** [comment] 2016-11-22 03:11
same here 👍

**Comment by PadraigK** [comment] 2016-11-22 20:00
We're seeing this too

**Comment by gmhawash** [comment] 2016-11-23 05:22
I am seeing this too and I thought it was some limitation in Redis (but I am sure that it worked before).

**Comment by badboy** [comment] 2016-11-23 07:34
Noted. The "fix" of another problem is the cause. [This PR might fix it](https://github.com/redis/redis-rb/pull/649).

Until merged and released, please use the previous version.

**Comment by djanowski** [comment] 2016-11-24 03:27
Can you all please test with redis-rb 4.0.0 RC1?

**Comment by gmhawash** [comment] 2016-11-24 12:49
This release appears to work for me.  Here is the test:
```
require 'bundler'
Bundler.require

require 'redis'
require 'Base64'

client = Redis.new timeout: 60

content = File.read("large-file.pdf")
p content.size
client.lpush 'test', content
client.set 'test2', content
```

**Comment by riseshia** [comment] 2016-11-28 07:57
Works well here, however, I can't used this version with rails 5. is there anything to do when we update to 4.x?
```
/Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- redis/distributed (LoadError)
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-store-1.2.0/lib/redis/distributed_store.rb:1:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-store-1.2.0/lib/redis-store.rb:4:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-rails-5.0.1/lib/redis-rails.rb:1:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
	from /Users/user/project/config/application.rb:9:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:156:in `require'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:77:in `console'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by badboy** [comment] 2016-11-28 08:05
We're removing [Redis::Distributed](https://github.com/redis/redis-rb/pull/653/commits/c4ebeda2e26d5182b832ad850f06fa2d72e3b77a). It might end up in another gem though.

**Comment by djanowski** [comment] 2016-11-28 14:58
Can you post the relevant Rails configuration? I'd like to know if this is
something required by Rails or something you configured. Thanks

**Comment by riseshia** [comment] 2016-11-29 01:03
now, Redis used for session_store, cache_store, sidekiq
Here is dependency related to redis:

- `redis-rails`
- `redis-namespace`
- `sidekiq`

I suspect `redis-rails` as a reason, [link](https://github.com/redis-store/redis-store/blob/master/lib/redis/distributed_store.rb) they use distributed store as default I guess ;_;

**Comment by tubbo** [comment] 2016-12-13 19:10
@riseshia redis-store determines which object to use by testing whether you're configuring multiple Redis servers. if so, it will use the `Redis::DistributedStore`, otherwise it will use the regular old `Redis::Store`...

https://github.com/redis-store/redis-store/blob/master/lib/redis/store/factory.rb#L19-L29

Unless there's a replacement for redis.rb's `Redis::Distributed` object, I'm not sure how we would account for this change downstream in redis-rails. You might be able to use Redis Sentinel to manage distributing the store to multiple servers? But I guess we're just waiting on that gem in order to allow upgrading to redis.rb 4.x...

**Comment by riseshia** [comment] 2016-12-15 02:01
OTL I see it. now, it's hard to introduce Redis Sentinel, it may be better to wait 4.x ;_;
Thanks to explanation @tubbo !

**Comment by le0pard** [comment] 2016-12-22 22:46
Hello. The same problem with redis-rb 3.3.2. After back to redis-rb 3.3.1 all works fine. Stack trace:
```
IO::EAGAINWaitWritable: Resource temporarily unavailable - write would block
  from <internal:prelude>:134:in `__write_nonblock'
  from <internal:prelude>:134:in `write_nonblock'
  from redis/connection/ruby.rb:105:in `_write_to_socket'
  from redis/connection/ruby.rb:131:in `block in write'
  from redis/connection/ruby.rb:130:in `loop'
  from redis/connection/ruby.rb:130:in `write'
  from redis/connection/ruby.rb:374:in `write'
  from redis/client.rb:271:in `block in write'
  from redis/client.rb:250:in `io'
  from redis/client.rb:269:in `write'
  from redis/client.rb:228:in `block (3 levels) in process'
  from redis/client.rb:222:in `each'
  from redis/client.rb:222:in `block (2 levels) in process'
  from redis/client.rb:367:in `ensure_connected'
  from redis/client.rb:221:in `block in process'
  from redis/client.rb:306:in `logging'
  from redis/client.rb:220:in `process'
  from redis/client.rb:120:in `call'
  from new_relic/agent/instrumentation/redis.rb:69:in `call'
  from redis.rb:769:in `block in setex'
  from redis.rb:58:in `block in synchronize'
  from monitor.rb:214:in `mon_synchronize'
  from redis.rb:58:in `synchronize'
  from redis.rb:768:in `setex'
  from redis/store/interface.rb:17:in `setex'
  from redis/store/marshalling.rb:13:in `block in setex'
  from redis/store/marshalling.rb:29:in `_marshal'
  from redis/store/marshalling.rb:13:in `setex'
  from redis/store/namespace.rb:11:in `block in setex'
  from redis/store/namespace.rb:84:in `namespace'
  from redis/store/namespace.rb:11:in `setex'
  from redis/store/ttl.rb:6:in `set'
  from redis/store/marshalling.rb:5:in `block in set'
  from redis/store/marshalling.rb:29:in `_marshal'
  from redis/store/marshalling.rb:5:in `set'
  from redis/store/namespace.rb:7:in `block in set'
  from redis/store/namespace.rb:84:in `namespace'
  from redis/store/namespace.rb:7:in `set'
  from active_support/cache/redis_store.rb:231:in `block in write_entry'
  from connection_pool.rb:64:in `block (2 levels) in with'
  from connection_pool.rb:63:in `handle_interrupt'
  from connection_pool.rb:63:in `block in with'
  from connection_pool.rb:60:in `handle_interrupt'
  from connection_pool.rb:60:in `with'
  from active_support/cache/redis_store.rb:218:in `with'
  from active_support/cache/redis_store.rb:231:in `write_entry'
  from active_support/cache/redis_store.rb:60:in `block in write'
  from active_support/cache.rb:562:in `block in instrument'
  from active_support/notifications.rb:166:in `instrument'
  from active_support/cache.rb:562:in `instrument'
  from active_support/cache/redis_store.rb:58:in `write'
  from config/initializers/rabl.rb:21:in `write'
  from rabl/helpers.rb:145:in `write_result_to_cache'
  from rabl/engine.rb:385:in `cache_results'
  from rabl/engine.rb:47:in `render'
  from rabl/builder.rb:127:in `block in merge_engines_into_result'
  from rabl/builder.rb:119:in `each'
  from rabl/builder.rb:119:in `merge_engines_into_result'
  from rabl/builder.rb:55:in `block in to_hash'
  from rabl/builder.rb:248:in `cache_results'
  from rabl/builder.rb:49:in `to_hash'
  from rabl/multi_builder.rb:27:in `map'
  from rabl/multi_builder.rb:27:in `to_a'
  from rabl/engine.rb:88:in `to_hash'
  from rabl/engine.rb:99:in `to_dumpable'
  from rabl/engine.rb:108:in `to_json'
  from rabl/engine.rb:48:in `block in render'
  from rabl/engine.rb:380:in `cache_results'
  from rabl/engine.rb:47:in `render'
```

rails 5.0.1
redis-rb 3.3.2
redis server 3.0.3
redis-rails 5.0.1

Happen randomly for using `Rails.cache.write`. Cache config:

```ruby
config.cache_store = :redis_store, "redis://localhost:6379/cache", {
    expires_in: 4.hours,
    pool_size: 10,
    pool_timeout: 10
 }
```

**Comment by tjoneseng** [comment] 2016-12-24 22:53
I started seeing this bug too when I upgraded from 3.3.1 to 3.3.2.

**Comment by cthulhu** [comment] 2016-12-30 10:17
Same here, after upgrade to 3.3.2 we had timeouts on big packages, solved by rolling back to 3.3.1

**Comment by salamagd** [comment] 2017-01-04 03:53
We're also seeing this with redis 3.3.2 and rails / redis-rails 5.0.1, getting `IO::EAGAINWaitWritable: Resource temporarily unavailable - write would block` causing a `Redis::TimeoutError` resulting in a `ActionView::Template::Error: Connection timed out` when rendering views that have large cached fragments, even with a huge timeout set. Pegging redis to 3.3.1 in our Gemfile has fixed it up.

**Comment by bobber205** [comment] 2017-01-05 19:27
Saw this issue while trying to write a key only 193KB in size. :|

**Comment by andrefreitas** [comment] 2017-01-16 09:30
I have the same issue in 3.3.2 when writing a 200 KB key size.

**Comment by djanowski** [comment] 2017-01-23 17:22
3.3.3 should fix this. Thank you.

**Closed by djanowski** 2017-01-23 17:22 UTC
Labels: bug

**Comment by tomandersen** [comment] 2017-02-10 00:59
The change of 3.3.2 to 3.3.3 in the Gemfile.lock fixed it for me. I was writing objects of about 50 - 200kB, and it seemed to fail for anything over ~100kB.
