### ISSUE TITLE
Unsupported command argument type: EtOrbi::EoTime

### ISSUE THREAD

**Issue by cristofer** [redis/redis-rb#1143] opened 2022-08-30 08:43 UTC
Hello guys,

After upgrading from 4.8.0 to 5.0.1, we get this error:

```
Unsupported command argument type: EtOrbi::EoTime |   | Exception during Sidekiq lifecycle event.
```

We saw that 5.0.0 was patched with some related issues with Sidekiq, could this still not be solved?

Thank you for your amazing work!

**Comment by byroot** [comment] 2022-08-30 08:51
Thanks for trying out 5.0.

It's hard to be 100% sure without the full backtrace, but based on the name of your type, I assume you are passing a complex type (`EtOrbi::EoTime`), as an `expiry` or `ttl` argument through Sidekiq.

In 4.x Redis would call `to_s` on arguments, but this is super error prone because `Object.new.to_s #=> "#<Object:0x00007fa65f16e8f8>"` which is certainly not what you want.

So you need to explicitly cast that `EtOrbi::EoTime` to one of the types that are understood by `redis-rb`. The supported types are documented in redis-client: https://github.com/redis-rb/redis-client#type-support

**Comment by byroot** [comment] 2022-08-30 10:24
Closing as I don't think there's much to do on my side.

If it appears that the issue isn't in your code but in some kind of gem and you don't know how to fix it yourself, feel free to post the full backtrace and I'll see about getting that gem compatible with redis 5.0.

**Closed by byroot** 2022-08-30 10:24 UTC

**Comment by cristofer** [comment] 2022-08-30 11:46
thanks your quick answer @byroot ! will debug deeper in our side then.

**Comment by raivil** [comment] 2022-09-06 01:09
I'm facing the same issues but I believe the error might be from another gem (sidekiq-scheduler).

Here's my current stack trace just for reference:
```
2022-09-05 21:27:43.056066 W [22474:9580] Sidekiq -- TypeError: Unsupported command argument type: EtOrbi::EoTime
2022-09-05 21:27:43.056077 W [22474:9580] Sidekiq -- /installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.3/lib/redis_client/command_builder.rb:37:in `block in generate'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.3/lib/redis_client/command_builder.rb:28:in `map!'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.3/lib/redis_client/command_builder.rb:28:in `generate'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-client-0.7.3/lib/redis_client.rb:203:in `call_v'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.2/lib/redis/client.rb:79:in `call_v'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.2/lib/redis.rb:167:in `block in send_command'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.2/lib/redis.rb:166:in `synchronize'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.2/lib/redis.rb:166:in `send_command'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/redis-5.0.2/lib/redis/commands/hashes.rb:26:in `hset'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:201:in `block in hset'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:164:in `block in redis'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq.rb:161:in `redis'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:201:in `hset'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/redis_manager.rb:63:in `set_job_next_time'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/utils.rb:127:in `update_job_next_time'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:120:in `block in load_schedule_job'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:111:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:111:in `load_schedule_job'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:89:in `block in load_schedule!'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:87:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/scheduler.rb:87:in `load_schedule!'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler/manager.rb:33:in `start'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.2/lib/sidekiq-scheduler.rb:24:in `block (2 levels) in <main>'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:57:in `block in fire_event'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:56:in `each'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/component.rb:56:in `fire_event'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/lib/sidekiq/cli.rb:105:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.5.5/bin/sidekiq:31:in `<top (required)>'
/installs/ruby/3.1.2/bin/sidekiq:25:in `load'
/installs/ruby/3.1.2/bin/sidekiq:25:in `<top (required)>'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `load'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
/installs/ruby/3.1.2/bin/bundle:25:in `load'
/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by casperisfine** [comment] 2022-09-06 08:40
Thanks @raivil for the backtrace. I made a PR to sidekiq-scheduler: https://github.com/sidekiq-scheduler/sidekiq-scheduler/pull/404

**Comment by casperisfine** [comment] 2022-09-06 14:52
My PR was merged upstream.
