### ISSUE TITLE
SORT_RO support

### ISSUE THREAD

**Issue by amree** [redis/redis-rb#1234] opened 2023-11-08 02:09 UTC
May I know if we can run something like `redis.sort_ro` on the replicas? It doesn't seem to be supported based on the code

https://github.com/redis/redis-rb/blob/2b183addb9175641a48e1d8616772282a31c0532/lib/redis/commands/keys.rb#L389

Related issue: https://github.com/redis/redis-rb/issues/525

**Comment by byroot** [comment] 2023-11-08 06:07
Duplicate of https://github.com/redis/redis-rb/issues/1187

PRs to support for Redis 7.0 commands are welcome. In the meantime you can issue any arbitrary comands with `.call`.

**Closed by byroot** 2023-11-08 06:07 UTC
