### ISSUE TITLE
New pipeline syntax works in v4.5.1, breaks with v4.6.0

### ISSUE THREAD

**Issue by VikiAnn** [redis/redis-rb#1082] opened 2022-02-25 23:15 UTC
Hi! I hope you can help me figure this out. We use redis-rb with [connection_pool](https://github.com/mperham/connection_pool) in my company's app, and we've got a PR upgrading to 4.6.0 that's been failing builds using the new pipeline syntax. I'm not sure if it's a problem with our code, a problem with redis-rb, or a problem with connection_pool (I think probably not, because playing with it in pry using just the redis client has the same problem.) We have some code that looks like this:
```ruby
# redis here is a wrapper method that passes the block to `connection_pool.with(&block)`; conn is actually the redis instance
redis do |conn|
  conn.pipelined do
    # profiles is an array where each looks like this: ['foo', { 'bar' => 'baz' }]
    profiles.each do |profile|
      visitor_id, data = profile
      key = "visitor-#{visitor_id}"

      conn.set(key, data.to_json)
    end
  end
end
```

In trying to resolve the deprecation warnings we changed that to:
```ruby
redis do |conn|
  conn.pipelined do |pipeline|
    profiles.each do |profile|
      visitor_id, data = profile
      key = key(visitor_id)

      pipeline.set(key, data.to_json)
    end
  end
end
```
That however does not seem to be successfully setting the key values, so our tests fail. Testing it out in pry has the same result on v4.6.0, but oddly enough, the same code in v4.5.1 works:

#### In pry on v4.5.1
```ruby
Container[:serialized_redis]
# => #<ConnectionPool:0x00007ff4da549558
#  @available=
#   #<ConnectionPool::TimedStack:0x00007ff4da5494b8
#    @create_block=#<Proc:0x00007ff4da549508 /Users/viki/src/broadlume/tatami/system/common/boot/serialized_redis.rb:34>,
#    @created=0,
#    @max=5,
#    @mutex=#<Thread::Mutex:0x00007ff4da549468>,
#    @que=[],
#    @resource=#<Thread::ConditionVariable:0x00007ff4da549440>,
#    @shutdown_block=nil>,
#  @key=:"pool-67320",
#  @key_count=:"pool-67320-count",
#  @size=5,
#  @timeout=3>
redis = Container[:serialized_redis].with {_1}
# => #<Redis client v4.5.1 for redis://localhost:6380/0>
profiles = [
  ['foo', { 'bar' => 'baz' }],
  ['qux', { 'quux' => 'corge' }]
]
# => [["foo", {"bar"=>"baz"}], ["qux", {"quux"=>"corge"}]]
redis.pipelined do |pipeline|
  profiles.each do |profile|
    key = "visitor-#{profile[0]}"
    pipeline.set(key, profile[1].to_json)
  end
end
# => ["OK", "OK"]
redis.get('visitor-foo')
# => "{\"bar\":\"baz\"}"
redis.get('visitor-qux')
# => "{\"quux\":\"corge\"}"
```

#### In pry on v4.6.0
```ruby
Container[:serialized_redis]
# => #<ConnectionPool:0x00007fb60fde8240
#  @available=
#   #<ConnectionPool::TimedStack:0x00007fb60fde81a0
#    @create_block=#<Proc:0x00007fb60fde81f0 /Users/viki/src/broadlume/tatami/system/common/boot/serialized_redis.rb:34>,
#    @created=1,
#    @max=5,
#    @mutex=#<Thread::Mutex:0x00007fb60fde8150>,
#    @que=[#<Redis client v4.6.0 for redis://localhost:6380/0>],
#    @resource=#<Thread::ConditionVariable:0x00007fb60fde8128>,
#    @shutdown_block=nil>,
#  @key=:"pool-67260",
#  @key_count=:"pool-67260-count",
#  @size=5,
#  @timeout=3>
profiles = [
  ['foo', { 'bar' => 'baz' }],
  ['qux', { 'quux' => 'corge' }]
]
# => [["foo", {"bar"=>"baz"}], ["qux", {"quux"=>"corge"}]]
redis = Container[:serialized_redis].with {_1}
# => #<Redis client v4.6.0 for redis://localhost:6380/0>
redis.pipelined do |pipeline|
  profiles.each do |profile|
    key = "visitor-#{profile[0]}"
    pipeline.set(key, profile[1].to_json)
  end
end  
# => ["OK", "OK"]
redis.get('visitor-foo')
# => "{\"bar\":\"baz\"}"
redis.get('visitor-qux')
# => "{\"quux\":\"corge\"}"
```

Thanks in advance for any insight you can provide 🙏

**Comment by byroot** [comment] 2022-02-25 23:39
I'm sorry I don't follow.

From your snippets your get the same results in both versions:

```
# => ["OK", "OK"]
redis.get('visitor-foo')
# => "{\"bar\":\"baz\"}"
redis.get('visitor-qux')
# => "{\"quux\":\"corge\"}"
```

What's the problem?

**Comment by VikiAnn** [comment] 2022-03-01 00:36
Ahhh I'm sorry, I have no idea what I did there but I guess I messed something up between copy/paste and then trying to clean it up. Here's the unedited output:
```
[1] franchises-development(main)> Container[:serialized_redis]
=> #<ConnectionPool:0x00007fe943d02df0
 @available=
  #<ConnectionPool::TimedStack:0x00007fe943d02d50
   @create_block=#<Proc:0x00007fe943d02da0 /Users/viki/src/broadlume/tatami/system/common/boot/serialized_redis.rb:34>,
   @created=0,
   @max=5,
   @mutex=#<Thread::Mutex:0x00007fe943d02cd8>,
   @que=[],
   @resource=#<Thread::ConditionVariable:0x00007fe943d02cb0>,
   @shutdown_block=nil>,
 @key=:"pool-67260",
 @key_count=:"pool-67260-count",
 @size=5,
 @timeout=3>
[2] franchises-development(main)> profiles = [
  ['foo', { 'bar' => 'baz' }],
  ['qux', { 'quux' => 'corge' }]
[2] franchises-development(main)> profiles = [
  ['foo', { 'bar' => 'baz' }],
  ['qux', { 'quux' => 'corge' }]
=> [["foo", {"bar"=>"baz"}], ["qux", {"quux"=>"corge"}]]
[3] franchises-development(main)> redis = Container[:serialized_redis].with {_1}
=> #<Redis client v4.6.0 for redis://localhost:6380/0>
[4] franchises-development(main)> redis.pipelined do |pipeline|
  profiles.each do |profile|
    key = "visitor-#{profile[0]}"
    pipeline.set(key, profile[1].to_json)
[4] franchises-development(main)> redis.pipelined do |pipeline|
  profiles.each do |profile|
    key = "visitor-#{profile[0]}"
    pipeline.set(key, profile[1].to_json)
  end
=> ["OK", "OK"]
[5] franchises-development(main)> redis.get('visitor-foo')
=> nil
[6] franchises-development(main)> redis.get('visitor-qux')
=> nil
```

**Comment by byroot** [comment] 2022-03-01 08:52
Ok, so no idea what's going on with you app. This works as expected:

```ruby
require 'redis'
require 'json'

profiles = [
  ['foo', { 'bar' => 'baz' }],
  ['qux', { 'quux' => 'corge' }]
]

redis = Redis.new

redis.pipelined do |pipeline|
  profiles.each do |profile|
    key = "visitor-#{profile[0]}"
    pipeline.set(key, profile[1].to_json)
  end
end

p redis.get('visitor-foo')
p redis.get('visitor-qux')
```

So I can only assume you have some gem or something incompatible with 4.6.0, but since I don't have access to your app I can't help you.

I'll close this issue as it's not actionable in this state. However if you do manage to reproduce it outside of your app, I'll hapily reopen.

**Closed by byroot** 2022-03-01 08:52 UTC

**Comment by VikiAnn** [comment] 2022-03-02 16:24
Ok, thank you for taking a look
