### ISSUE TITLE
Multi/exec blocks are not retried on error

### ISSUE THREAD

**Issue by jdheyburn** [redis/redis-rb#1285] opened 2024-08-01 15:58 UTC
I'm seeing that our multi/exec calls defined as below are not retried in the event of an error, despite `reconnect_attempts` > 0. This isn't the case for our other commands.

```ruby
redis.multi do |multi|
  multi.set("foo", "bar")
end
```

I wanted to add a test for this but I am not well-versed in Ruby. Is this by design or a bug?

**Comment by byroot** [comment] 2024-08-01 18:21
> Is this by design or a bug?

It's not by design, but I also have no indication this bug exists, because the code is very explicit about retrying them.

So unless you got some test or reproduction, this issue won't be actionable for me.

**Comment by byroot** [comment] 2024-08-02 06:13
Closing until a reproduction is provided.

**Closed by byroot** 2024-08-02 06:13 UTC
