### ISSUE TITLE
Error connecting to Redis on ElastiCache

### ISSUE THREAD

**Issue by cilim** [redis/redis-rb#648] opened 2016-11-09 12:16 UTC
I cannot connect to my ElastiCache cluster for some reason.

I'm using v3.3.1 of the gem and the default port 6379.

Here's what I did:

```
[1] pry(main)> require 'redis'
=> true
[2] pry(main)> cache = Redis.new(host: 'cilim2.wnaben.ng.0001.apse2.cache.amazonaws.com')
=> #<Redis client v3.3.1 for redis://cilim2.wnaben.ng.0001.apse2.cache.amazonaws.com:6379/0>
[3] pry(main)> cache.connected
Redis::CannotConnectError: Error connecting to Redis on cilim2.wnaben.ng.0001.apse2.cache.amazonaws.com:6379 (Redis::TimeoutError)
from /Users/cilim/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-3.3.1/lib/redis/client.rb:345:in `rescue in establish_connection'
```

**Comment by badboy** [comment] 2016-11-09 12:17
Figure out why a connection to the server times out. Can you connect using telnet/netcat? If not, debug that (maybe some firewall rules).

In any case, this is not a bug in redis-rb. Closing.

**Closed by badboy** 2016-11-09 12:17 UTC
